version: '3.9'
services:
  postgres-db:
    image: postgres:16
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev
      
  backend:
    image: ghcr.io/wk981/wk-fyp-backend:latest
    # build: ./wgtpivotlo-backend
    tty: true
    # ports:
    # - 8080:8080
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_URL: ${PG_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      SHOW_SQL: ${SHOW_SQL}
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    networks:
      - dev

  frontend:
    image: ghcr.io/wk981/wk-fyp-frontend:latest
    # build: ./wgtpivotlo-frontend
    tty: true
    ports:
      - 127.0.0.1:7000:7000
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      SERVER_NAME: ${SERVER_NAME}
    networks:
      - dev
      
volumes:
  pgdata: 
networks:
  dev: