version: '3.9'
services:
  postgres-db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev
      
  backend:
    image: ghcr.io/wk981/wk-fyp-backend:latest
    # build: ./wgtpivotlo-backend
    tty: true
    # ports:
    # - 8080:8080
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_URL: ${PG_URL}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - dev

  frontend:
    image: ghcr.io/wk981/wk-fyp-frontend:latest
    # build: ./wgtpivotlo-frontend
    tty: true
    # ports:
    #   - 80:80
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    networks:
      - dev
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./reverse-proxy:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/server-name-replace-here/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/server-name-replace-here/privkey.pem:/etc/nginx/ssl/privkey.pem
    networks:
      - dev
    environment:
      - SERVER_NAME=${SERVER_NAME}

volumes:
  pgdata: 
networks:
  dev: