version: '3.9'
services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wgtpivotlo-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 