name: Backend cicd
on:
    push:
      branches:
        - main
        - feat/cicd
      paths: 
        - 'wgtpivotlo-backend/**'
jobs:
    Unit_Tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 23
          uses: actions/setup-java@v4
          with:
            java-version: '23'
            distribution: 'temurin'
            cache: maven
        - name: Perform Unit Test
          run: |
              cd wgtpivotlo-backend
              mvn clean install --batch-mode
    
    Build_and_Push_image:
      runs-on: ubuntu-latest
      needs: Unit_Tests
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 23
          uses: actions/setup-java@v4
          with:
            java-version: '23'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          run: |
              cd wgtpivotlo-backend
              mvn clean package -DskipTests=true
        - name: Publish to GHCR
          run: |
            echo "${{secrets.GHCR_PAT}}" | docker login ghcr.io --username ${{secrets.USERNAME}} --password-stdin  
        - name: Build Docker Image
          run: 
            docker build . --tag ghcr.io/${{secrets.USERNAME}}/wk-fyp-backend:latest
        - name: Push Docker Image
          run:
            docker push ghcr.io/${{secrets.USERNAME}}/wk-fyp-backend:latest

