name: Frontend cicd
on:
    push:
      branches:
        - main
        - feat/cicd
      # paths: 
      #   - 'wgtpivotlo-frontend/**'
jobs:
    Unit_Tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
        - name: npm install
          run: |
              cd wgtpivotlo-frontend
              npm install
        - name: Perform Unit Test
          run: |
              cd wgtpivotlo-frontend
              npm run lint
    
    Build_and_Push_image:
      runs-on: ubuntu-latest
      needs: Unit_Tests
      steps:
        - uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
        - name: Docker Login
          run: |
              echo "${{secrets.GHCR_PAT}}" | docker login ghcr.io --username ${{secrets.USERNAME}} --password-stdin  
        - name: Build Docker Image
          run: |
              cd wgtpivotlo-frontend
              docker build . --tag ghcr.io/${{ secrets.USERNAME }}/wk-fyp-frontend:latest
        - name: Push Docker Image
          run:
              docker push ghcr.io/${{ secrets.USERNAME }}/wk-fyp-frontend:latest

